<?php
/**
 * Pursuarr — a better search interface for Prowlarr (single file, no dependencies).
 *
 * Drop this file into a web root and open it. Requires PHP 8.1+ with ext-curl.
 *
 * SECURITY: There is NO application authentication by design. Anyone who can reach
 * this app can search, grab releases and edit settings (including the Prowlarr URL
 * and API key). Protect this path — ideally the whole vhost — at your reverse proxy
 * (basic auth, VPN, tailscale, IP allowlist ...). The Prowlarr API key never reaches
 * the browser; it lives only in settings.php (chmod 0600, kept outside the docroot
 * when possible, else denied via .htaccess).
 */
declare(strict_types=1);

const PURSUARR_VERSION = '1.0.0';
const PURSUARR_MAX_GRAB_BODY = 65536;
const PURSUARR_SEARCH_TYPES = ['search', 'tvsearch', 'movie', 'music', 'book'];

function pursuarr_h(?string $s): string
{
    return htmlspecialchars((string)$s, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

function pursuarr_json($data, int $code = 200): void
{
    http_response_code($code);
    header('Content-Type: application/json; charset=utf-8');
    echo json_encode($data, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_UNESCAPED_SLASHES);
    exit;
}

/* ---------------------------------------------------------------- config --- */

function pursuarr_default_settings(): array
{
    return [
        'prowlarr_url' => 'http://localhost:9696',
        'prowlarr_api_key' => '',
        'expansion_groups' => [
            ['x265', 'h265', 'HEVC'],
            ['x264', 'h264', 'AVC'],
        ],
        'max_search_variants' => 5,
        'default_limit' => 100,
        'search_timeout' => 90,
        'download_client_id' => null,
        'verify_tls' => true,
    ];
}

function pursuarr_settings_candidates(): array
{
    $out = [];
    $env = getenv('PURSUARR_SETTINGS');
    if (is_string($env) && trim($env) !== '') {
        $out[] = $env;
    }
    $out[] = __DIR__ . '/../settings.php';
    $out[] = __DIR__ . '/settings.php';
    return array_values(array_unique($out));
}

function pursuarr_normalize_settings(array $raw): array
{
    $d = pursuarr_default_settings();
    $s = array_merge($d, $raw);

    $url = trim((string)$s['prowlarr_url']);
    if ($url !== '' && !preg_match('#^https?://#i', $url)) {
        $url = 'http://' . $url;
    }
    $s['prowlarr_url'] = rtrim($url, '/');

    $s['prowlarr_api_key'] = trim((string)$s['prowlarr_api_key']);
    $s['max_search_variants'] = max(1, min(20, (int)$s['max_search_variants']));
    $s['default_limit'] = max(1, min(1000, (int)$s['default_limit']));
    $s['search_timeout'] = max(5, min(600, (int)$s['search_timeout']));

    $dc = trim((string)($s['download_client_id'] ?? ''));
    $s['download_client_id'] = $dc === '' ? null : (is_numeric($dc) ? (int)$dc : $dc);

    $s['verify_tls'] = (bool)$s['verify_tls'];

    $groups = [];
    foreach ((array)$s['expansion_groups'] as $group) {
        if (!is_array($group)) {
            continue;
        }
        $members = [];
        foreach ($group as $m) {
            $m = trim((string)$m);
            if ($m !== '' && !in_array($m, $members, true)) {
                $members[] = $m;
            }
        }
        if (count($members) > 0) {
            $groups[] = $members;
        }
    }
    $s['expansion_groups'] = $groups;

    return $s;
}

function pursuarr_load_settings(): ?array
{
    static $cached = false;
    static $value = null;
    if ($cached) {
        return $value;
    }
    $cached = true;
    foreach (pursuarr_settings_candidates() as $path) {
        if (is_file($path)) {
            $data = require $path;
            if (is_array($data)) {
                $value = pursuarr_normalize_settings($data);
                return $value;
            }
        }
    }
    return null;
}

function pursuarr_write_settings(array $settings): array
{
    $export = var_export($settings, true);
    $php = "<?php\n// Pursuarr settings file — generated by the app. Keep out of reach of the web.\nreturn " . $export . ";\n";
    foreach (pursuarr_settings_candidates() as $path) {
        $dir = dirname($path);
        if (!is_dir($dir) || !is_writable($dir)) {
            continue;
        }
        if (is_file($path) && !is_writable($path)) {
            continue;
        }
        if (@file_put_contents($path, $php) === false) {
            continue;
        }
        @chmod($path, 0600);
        if (function_exists('opcache_invalidate')) {
            @opcache_invalidate($path, true);
        }
        if (realpath($dir) === realpath(__DIR__)) {
            pursuarr_write_htaccess($dir);
        }
        return ['ok' => true, 'path' => $path, 'error' => null];
    }
    return [
        'ok' => false,
        'path' => '',
        'error' => 'Could not write settings.php (tried ' . implode(', ', pursuarr_settings_candidates()) . '). Check directory permissions.',
    ];
}

function pursuarr_write_htaccess(string $dir): void
{
    $path = $dir . '/.htaccess';
    $rule = "<Files settings.php>\n    Require all denied\n</Files>\n";
    if (is_file($path)) {
        $existing = (string)@file_get_contents($path);
        if (str_contains($existing, 'settings.php')) {
            return;
        }
        @file_put_contents($path, rtrim($existing) . "\n\n" . $rule);
        return;
    }
    @file_put_contents($path, $rule);
}

function pursuarr_settings_exposed_url(string $path): ?string
{
    $docroot = (string)($_SERVER['DOCUMENT_ROOT'] ?? '');
    if ($docroot === '') {
        return null;
    }
    $rp = realpath($path);
    $rd = realpath($docroot);
    if ($rp === false || $rd === false || $rp === $rd) {
        return null;
    }
    if (!str_starts_with($rp, rtrim($rd, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR)) {
        return null;
    }
    $rel = substr($rp, strlen(rtrim($rd, DIRECTORY_SEPARATOR)) + 1);
    $rel = str_replace(DIRECTORY_SEPARATOR, '/', $rel);
    $https = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')
        || (($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? '') === 'https');
    $scheme = $https ? 'https' : 'http';
    $host = (string)($_SERVER['HTTP_HOST'] ?? 'localhost');
    $url = $scheme . '://' . $host . '/' . str_replace(' ', '%20', $rel);

    $ch = curl_init($url);
    if ($ch === false) {
        return null;
    }
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_TIMEOUT => 5,
        CURLOPT_CONNECTTIMEOUT => 3,
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_SSL_VERIFYHOST => 0,
    ]);
    $body = curl_exec($ch);
    $code = (int)curl_getinfo($ch, CURLINFO_RESPONSE_CODE);
    if ($code !== 200 || !is_string($body) || $body === '') {
        return null;
    }
    if (str_contains($body, '<?php') || str_contains($body, 'prowlarr_api_key') || str_contains($body, "return ")) {
        return $url;
    }
    return null;
}

/* ------------------------------------------------------------ http client --- */

function pursuarr_api_url(array $settings, string $path): string
{
    return $settings['prowlarr_url'] . '/api/v1' . $path;
}

function pursuarr_build_query(array $params): string
{
    $parts = [];
    foreach ($params as $key => $value) {
        if ($value === null || $value === '') {
            continue;
        }
        if (is_array($value)) {
            foreach ($value as $item) {
                if ($item === null || $item === '') {
                    continue;
                }
                $parts[] = rawurlencode((string)$key) . '=' . rawurlencode((string)$item);
            }
            continue;
        }
        $parts[] = rawurlencode((string)$key) . '=' . rawurlencode((string)$value);
    }
    return implode('&', $parts);
}

function pursuarr_curl_error_message(int $errno, string $error): string
{
    $host = 'Prowlarr';
    return match (true) {
        $errno === CURLE_COULDNT_CONNECT => "Can't connect to {$host} — is it running and reachable from this server?",
        $errno === CURLE_COULDNT_RESOLVE_HOST => "Can't resolve the Prowlarr host name — check the base URL in settings.",
        $errno === CURLE_COULDNT_RESOLVE_PROXY => "Can't resolve the HTTP proxy — check proxy settings.",
        $errno === CURLE_OPERATION_TIMEOUTED => "Request to Prowlarr timed out. Prowlarr may still be waiting on indexers (FlareSolverr can take 60s+).",
        $errno === CURLE_SSL_CONNECT_ERROR || $errno === CURLE_PEER_FAILED_VERIFICATION => "TLS error talking to Prowlarr — for self-signed certs disable 'verify TLS' in settings.",
        $errno === CURLE_GOT_NOTHING => "Prowlarr closed the connection without a response.",
        default => "Network error talking to Prowlarr" . ($error !== '' ? " ({$error})" : " (cURL {$errno})"),
    };
}

function pursuarr_http_error_message(int $code, string $body): string
{
    $snippet = trim(preg_replace('/\s+/', ' ', strip_tags($body)) ?? '');
    $snippet = mb_substr($snippet, 0, 200);
    $detail = '';
    $decoded = json_decode($body, true);
    if (is_array($decoded)) {
        foreach (['message', 'description', 'error', 'title'] as $k) {
            if (isset($decoded[$k]) && is_string($decoded[$k]) && $decoded[$k] !== '') {
                $detail = mb_substr(preg_replace('/\s+/', ' ', $decoded[$k]) ?? '', 0, 200);
                break;
            }
        }
    }
    if ($detail === '' && $snippet !== '') {
        $detail = $snippet;
    }
    return match (true) {
        $code === 401 => '401 Unauthorized — check the API key in settings' . ($detail !== '' ? " ({$detail})" : ''),
        $code === 403 => '403 Forbidden — the API key is not allowed to do this' . ($detail !== '' ? " ({$detail})" : ''),
        $code === 404 => '404 Not Found — check the Prowlarr base URL in settings' . ($detail !== '' ? " ({$detail})" : ''),
        default => "HTTP {$code} from Prowlarr" . ($detail !== '' ? ": {$detail}" : ''),
    };
}

function pursuarr_decode_body(string $body): array
{
    $decoded = json_decode($body, true);
    if (!is_array($decoded)) {
        $snippet = trim(preg_replace('/\s+/', ' ', strip_tags($body)) ?? '');
        $snippet = mb_substr($snippet, 0, 120);
        return ['ok' => false, 'error' => 'Invalid JSON response from Prowlarr' . ($snippet !== '' ? " (got: {$snippet})" : ''), 'json' => null];
    }
    return ['ok' => true, 'error' => null, 'json' => $decoded];
}

function pursuarr_build_curl(string $url, array $settings, ?int $timeoutSec = null, ?string $apiKey = null): \CurlHandle
{
    $key = $apiKey ?? (string)$settings['prowlarr_api_key'];
    $verify = (bool)($settings['verify_tls'] ?? true);
    $ch = curl_init($url);
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_HTTPHEADER => [
            'Accept: application/json',
            'X-Api-Key: ' . $key,
        ],
        CURLOPT_CONNECTTIMEOUT => 5,
        CURLOPT_TIMEOUT => $timeoutSec ?? (int)$settings['search_timeout'],
        CURLOPT_SSL_VERIFYPEER => $verify,
        CURLOPT_SSL_VERIFYHOST => $verify ? 2 : 0,
        CURLOPT_PROTOCOLS => CURLPROTO_HTTP | CURLPROTO_HTTPS,
        CURLOPT_FOLLOWLOCATION => false,
    ]);
    return $ch;
}

function pursuarr_request_json(
    string $method,
    string $path,
    array $settings,
    ?array $query = null,
    ?array $body = null,
    ?int $timeoutSec = null
): array {
    $url = pursuarr_api_url($settings, $path);
    $qs = $query !== null ? pursuarr_build_query($query) : '';
    if ($qs !== '') {
        $url .= '?' . $qs;
    }
    $ch = pursuarr_build_curl($url, $settings, $timeoutSec);
    if (strtoupper($method) === 'POST') {
        $payload = json_encode($body ?? new stdClass(), JSON_HEX_TAG);
        curl_setopt_array($ch, [
            CURLOPT_POST => true,
            CURLOPT_POSTFIELDS => (string)$payload,
            CURLOPT_HTTPHEADER => [
                'Accept: application/json',
                'Content-Type: application/json',
                'X-Api-Key: ' . (string)$settings['prowlarr_api_key'],
            ],
        ]);
    }
    $respBody = curl_exec($ch);
    $errno = curl_errno($ch);
    $err = curl_error($ch);
    $code = (int)curl_getinfo($ch, CURLINFO_RESPONSE_CODE);

    if (!is_string($respBody)) {
        return ['ok' => false, 'error' => pursuarr_curl_error_message($errno, $err), 'json' => null, 'http_code' => $code];
    }
    if ($errno !== 0) {
        return ['ok' => false, 'error' => pursuarr_curl_error_message($errno, $err), 'json' => null, 'http_code' => $code];
    }
    if ($code >= 400) {
        return ['ok' => false, 'error' => pursuarr_http_error_message($code, $respBody), 'json' => null, 'http_code' => $code];
    }
    $decoded = pursuarr_decode_body($respBody);
    return ['ok' => $decoded['ok'], 'error' => $decoded['error'], 'json' => $decoded['json'], 'http_code' => $code];
}

function pursuarr_search_multi(array $queries, array $common, array $settings): array
{
    $timeout = (int)$settings['search_timeout'];
    $mh = curl_multi_init();
    $handles = [];
    foreach ($queries as $i => $q) {
        $params = $common;
        $params['query'] = $q;
        $url = pursuarr_api_url($settings, '/search') . '?' . pursuarr_build_query($params);
        $ch = pursuarr_build_curl($url, $settings, $timeout);
        curl_multi_add_handle($mh, $ch);
        $handles[$i] = $ch;
    }

    do {
        $status = curl_multi_exec($mh, $running);
        if ($running > 0) {
            $sel = curl_multi_select($mh, 1.0);
            if ($sel === -1) {
                usleep(20000);
            }
        }
    } while ($running > 0 && $status === CURLM_OK);

    $multiErrors = [];
    while (($info = curl_multi_info_read($mh, $queued)) !== false) {
        $result = (int)($info['result'] ?? 0);
        if ($result !== 0) {
            $multiErrors[spl_object_id($info['handle'])] = $result;
        }
    }

    $out = [];
    foreach ($handles as $i => $ch) {
        $body = curl_multi_getcontent($ch);
        $errno = $multiErrors[spl_object_id($ch)] ?? curl_errno($ch);
        $err = curl_error($ch);
        $code = (int)curl_getinfo($ch, CURLINFO_RESPONSE_CODE);
        $entry = ['query' => (string)$queries[$i], 'ok' => false, 'results' => [], 'error' => null];
        if ($errno !== 0) {
            $entry['error'] = pursuarr_curl_error_message($errno, $err);
        } elseif ($code >= 400) {
            $entry['error'] = pursuarr_http_error_message($code, is_string($body) ? $body : '');
        } else {
            $decoded = pursuarr_decode_body(is_string($body) ? $body : '');
            if (!$decoded['ok']) {
                $entry['error'] = $decoded['error'];
            } elseif (!array_is_list($decoded['json'])) {
                $entry['error'] = 'Unexpected response from Prowlarr search endpoint.';
            } else {
                $entry['ok'] = true;
                $entry['results'] = $decoded['json'];
            }
        }
        curl_multi_remove_handle($mh, $ch);
        $out[$i] = $entry;
    }
    curl_multi_close($mh);
    return $out;
}

/* ---------------------------------------------------------------- parser --- */

function pursuarr_tokenize(string $query): array
{
    $tokens = [];
    $len = strlen($query);
    $i = 0;
    while ($i < $len) {
        $c = $query[$i];
        if ($c === ' ' || $c === "\t" || $c === "\n" || $c === "\r") {
            $i++;
            continue;
        }
        $neg = false;
        if ($c === '-' && $i + 1 < $len && !ctype_space($query[$i + 1])) {
            $neg = true;
            $i++;
            $c = $query[$i];
        }
        if ($c === '"') {
            $i++;
            $start = $i;
            while ($i < $len && $query[$i] !== '"') {
                $i++;
            }
            $text = substr($query, $start, $i - $start);
            if ($i < $len) {
                $i++;
            }
            if ($text !== '') {
                $tokens[] = ['type' => $neg ? 'exact_exclude' : 'exact', 'text' => $text];
            }
            continue;
        }
        if ($c === '{') {
            $start = $i;
            while ($i < $len && $query[$i] !== '}') {
                $i++;
            }
            if ($i < $len) {
                $i++;
            }
            $text = substr($query, $start, $i - $start);
            if ($text !== '') {
                $tokens[] = ['type' => $neg ? 'exclude' : 'id', 'text' => $text];
            }
            continue;
        }
        $start = $i;
        while ($i < $len && !ctype_space($query[$i])) {
            $i++;
        }
        $text = substr($query, $start, $i - $start);
        if ($text !== '') {
            $tokens[] = ['type' => $neg ? 'exclude' : 'term', 'text' => $text];
        }
    }
    return $tokens;
}

function pursuarr_is_sent(array $token): bool
{
    return in_array($token['type'], ['term', 'exact', 'id'], true);
}

function pursuarr_base_query(array $tokens): string
{
    $parts = [];
    foreach ($tokens as $t) {
        if (pursuarr_is_sent($t)) {
            $parts[] = $t['text'];
        }
    }
    return implode(' ', $parts);
}

function pursuarr_plan_variants(array $tokens, array $groups, int $maxVariants): array
{
    $sent = [];
    foreach ($tokens as $t) {
        if (pursuarr_is_sent($t)) {
            $sent[] = $t;
        }
    }
    $altLists = [];
    foreach ($sent as $t) {
        $alts = [$t['text']];
        if ($t['type'] === 'term') {
            foreach ($groups as $group) {
                $hit = false;
                foreach ($group as $member) {
                    if (strcasecmp((string)$member, (string)$t['text']) === 0) {
                        $hit = true;
                        break;
                    }
                }
                if (!$hit) {
                    continue;
                }
                foreach ($group as $member) {
                    $member = (string)$member;
                    $dup = false;
                    foreach ($alts as $a) {
                        if (strcasecmp((string)$a, $member) === 0) {
                            $dup = true;
                            break;
                        }
                    }
                    if (!$dup) {
                        $alts[] = $member;
                    }
                }
            }
        }
        $altLists[] = $alts;
    }

    $combos = [[]];
    foreach ($altLists as $i => $alts) {
        if (count($alts) <= 1) {
            continue;
        }
        $next = [];
        foreach ($combos as $combo) {
            foreach ($alts as $a) {
                $combo2 = $combo;
                $combo2[$i] = $a;
                $next[] = $combo2;
            }
        }
        $combos = $next;
        if (count($combos) > 1024) {
            break;
        }
    }

    $variants = [];
    foreach ($combos as $combo) {
        $parts = [];
        foreach ($sent as $i => $t) {
            $parts[] = array_key_exists($i, $combo) ? $combo[$i] : $t['text'];
        }
        $q = implode(' ', $parts);
        if (!in_array($q, $variants, true)) {
            $variants[] = $q;
        }
    }
    return array_slice($variants, 0, max(1, $maxVariants));
}

function pursuarr_normalize_title_tokens(string $s): array
{
    $s = mb_strtolower($s, 'UTF-8');
    $s = (string)preg_replace('/[^\p{L}\p{N}]+/u', ' ', $s);
    $s = trim((string)preg_replace('/\s+/u', ' ', $s));
    return $s === '' ? [] : explode(' ', $s);
}

function pursuarr_contains_sequence(array $haystack, array $needle): bool
{
    $n = count($needle);
    $h = count($haystack);
    if ($n === 0) {
        return true;
    }
    if ($n > $h) {
        return false;
    }
    for ($i = 0; $i <= $h - $n; $i++) {
        $ok = true;
        for ($j = 0; $j < $n; $j++) {
            if ($haystack[$i + $j] !== $needle[$j]) {
                $ok = false;
                break;
            }
        }
        if ($ok) {
            return true;
        }
    }
    return false;
}

function pursuarr_post_filter(array $results, array $tokens): array
{
    $exclusions = [];
    $exacts = [];
    $exactExclusions = [];
    foreach ($tokens as $t) {
        if ($t['type'] === 'exclude') {
            $exclusions[] = mb_strtolower((string)$t['text'], 'UTF-8');
        } elseif ($t['type'] === 'exact') {
            $exacts[] = pursuarr_normalize_title_tokens((string)$t['text']);
        } elseif ($t['type'] === 'exact_exclude') {
            $exactExclusions[] = pursuarr_normalize_title_tokens((string)$t['text']);
        }
    }
    $out = [];
    foreach ($results as $r) {
        if (!is_array($r)) {
            continue;
        }
        $title = (string)($r['title'] ?? '');
        $titleLower = mb_strtolower($title, 'UTF-8');
        foreach ($exclusions as $e) {
            if ($e !== '' && str_contains($titleLower, $e)) {
                continue 2;
            }
        }
        $titleTokens = pursuarr_normalize_title_tokens($title);
        foreach ($exacts as $phrase) {
            if (!pursuarr_contains_sequence($titleTokens, $phrase)) {
                continue 2;
            }
        }
        foreach ($exactExclusions as $phrase) {
            if (pursuarr_contains_sequence($titleTokens, $phrase)) {
                continue 2;
            }
        }
        $out[] = $r;
    }
    return $out;
}

function pursuarr_dedupe(array $results): array
{
    $seen = [];
    $out = [];
    foreach ($results as $r) {
        if (!is_array($r)) {
            continue;
        }
        $guid = trim((string)($r['guid'] ?? ''));
        $key = $guid !== ''
            ? 'g:' . $guid
            : 'k:' . (string)($r['indexerId'] ?? '') . '|' . (string)($r['title'] ?? '') . '|' . (string)($r['size'] ?? '');
        if (isset($seen[$key])) {
            continue;
        }
        $seen[$key] = true;
        $out[] = $r;
    }
    return $out;
}

function pursuarr_list_param($value): array
{
    if ($value === null || $value === '') {
        return [];
    }
    $items = is_array($value) ? $value : explode(',', (string)$value);
    $out = [];
    foreach ($items as $item) {
        $item = trim((string)$item);
        if ($item !== '' && !in_array($item, $out, true)) {
            $out[] = $item;
        }
    }
    return $out;
}

function pursuarr_valid_type($type): string
{
    $type = strtolower(trim((string)$type));
    return in_array($type, PURSUARR_SEARCH_TYPES, true) ? $type : 'search';
}

/* ------------------------------------------------------------- settings UI --- */

function pursuarr_groups_to_text(array $groups): string
{
    $lines = [];
    foreach ($groups as $g) {
        $lines[] = implode(' | ', $g);
    }
    return implode("\n", $lines);
}

function pursuarr_parse_groups_text(string $text): array
{
    $groups = [];
    foreach (preg_split('/\R/', $text) as $line) {
        $line = trim($line);
        if ($line === '') {
            continue;
        }
        $members = [];
        foreach (explode('|', $line) as $part) {
            $part = trim($part);
            if ($part !== '' && !in_array($part, $members, true)) {
                $members[] = $part;
            }
        }
        if (count($members) > 0) {
            $groups[] = $members;
        }
    }
    return $groups;
}

function pursuarr_handle_settings_post(): void
{
    $current = pursuarr_load_settings() ?? pursuarr_default_settings();
    $verifyTls = isset($_POST['verify_tls']) && $_POST['verify_tls'] !== '' && $_POST['verify_tls'] !== '0';
    $candidate = pursuarr_normalize_settings([
        'prowlarr_url' => (string)($_POST['prowlarr_url'] ?? ''),
        'prowlarr_api_key' => (string)($_POST['prowlarr_api_key'] ?? ''),
        'expansion_groups' => pursuarr_parse_groups_text((string)($_POST['expansion_groups'] ?? '')),
        'max_search_variants' => (int)($_POST['max_search_variants'] ?? $current['max_search_variants']),
        'default_limit' => (int)($_POST['default_limit'] ?? $current['default_limit']),
        'search_timeout' => (int)($_POST['search_timeout'] ?? $current['search_timeout']),
        'download_client_id' => trim((string)($_POST['download_client_id'] ?? '')),
        'verify_tls' => $verifyTls,
    ]);

    if ($candidate['prowlarr_url'] === '' || preg_match('#^https?://$#i', $candidate['prowlarr_url'])) {
        pursuarr_render_settings($current, pursuarr_load_settings() === null, null, 'Prowlarr base URL is required.');
        return;
    }

    $test = pursuarr_request_json('GET', '/system/status', $candidate, null, null, 20);
    if (!$test['ok']) {
        pursuarr_render_settings($current, pursuarr_load_settings() === null, null, 'Connection test failed — settings not saved. ' . $test['error']);
        return;
    }

    $written = pursuarr_write_settings($candidate);
    if (!$written['ok']) {
        pursuarr_render_settings($current, pursuarr_load_settings() === null, null, $written['error']);
        return;
    }

    $notice = 'Settings saved to ' . $written['path'] . '.';
    $warn = pursuarr_settings_exposed_url($written['path']);
    if ($warn !== null) {
        $notice .= ' WARNING: settings.php is reachable over HTTP at ' . $warn . ' — move it out of the web root or deny access to it.';
    }
    pursuarr_render_settings($candidate, false, $notice, null);
}

/* ---------------------------------------------------------------- router --- */

function pursuarr_main(): void
{
    if (!function_exists('curl_init')) {
        pursuarr_render_fatal(
            'The PHP cURL extension is required but not loaded. Install/enable it '
            . '(e.g. <code>apt install php-curl</code>, <code>dnf install php-curl</code>, '
            . 'or uncomment <code>extension=curl</code> in php.ini) and reload this page.'
        );
    }

    $action = (string)($_GET['action'] ?? '');
    $method = strtoupper((string)($_SERVER['REQUEST_METHOD'] ?? 'GET'));
    $settings = pursuarr_load_settings();

    if ($settings === null && in_array($action, ['search', 'grab', 'indexers', 'categories'], true)) {
        pursuarr_json(['ok' => false, 'error' => 'Pursuarr is not configured yet — open the app and complete setup.'], 503);
    }

    if ($settings === null && !in_array($action, ['settings', 'status', 'parse'], true)) {
        pursuarr_render_settings(null, true, null, null);
        return;
    }

    switch ($action) {
        case '':
            pursuarr_render_app($settings ?? pursuarr_default_settings());
            return;

        case 'search':
            pursuarr_action_search($settings ?? pursuarr_default_settings());
            return;

        case 'grab':
            pursuarr_action_grab($settings ?? pursuarr_default_settings());
            return;

        case 'indexers':
            pursuarr_action_indexers($settings ?? pursuarr_default_settings());
            return;

        case 'categories':
            pursuarr_action_categories($settings ?? pursuarr_default_settings());
            return;

        case 'status':
            pursuarr_action_status($settings ?? pursuarr_default_settings());
            return;

        case 'parse':
            pursuarr_action_parse($settings ?? pursuarr_default_settings());
            return;

        case 'settings':
            if ($method === 'POST') {
                pursuarr_handle_settings_post();
                return;
            }
            pursuarr_render_settings($settings, $settings === null, $_GET['saved'] ?? null, null);
            return;

        default:
            pursuarr_render_app($settings ?? pursuarr_default_settings());
            return;
    }
}

function pursuarr_action_search(array $settings): void
{
    @set_time_limit(300);

    $query = (string)($_GET['query'] ?? '');
    $type = pursuarr_valid_type($_GET['type'] ?? 'search');
    $limit = (int)($_GET['limit'] ?? $settings['default_limit']);
    if ($limit <= 0) {
        $limit = (int)$settings['default_limit'];
    }
    $limit = max(1, min(1000, $limit));

    $indexerIds = pursuarr_list_param($_GET['indexerIds'] ?? null);
    $categories = pursuarr_list_param($_GET['categories'] ?? null);

    $tokens = pursuarr_tokenize($query);
    $variants = pursuarr_plan_variants($tokens, $settings['expansion_groups'], (int)$settings['max_search_variants']);

    if ($variants === [] || $variants[0] === '') {
        pursuarr_json([
            'results' => [],
            'variantsUsed' => [],
            'errors' => [['variant' => '', 'error' => 'Query contains no searchable terms (only exclusions). Add at least one term to search.']],
        ]);
        return;
    }

    $common = ['type' => $type, 'limit' => $limit];
    if ($indexerIds !== []) {
        $common['indexerIds'] = $indexerIds;
    }
    if ($categories !== []) {
        $common['categories'] = $categories;
    }

    $perVariant = pursuarr_search_multi($variants, $common, $settings);

    $results = [];
    $errors = [];
    $used = [];
    foreach ($perVariant as $entry) {
        $used[] = $entry['query'];
        if (!$entry['ok']) {
            $errors[] = ['variant' => $entry['query'], 'error' => $entry['error']];
            continue;
        }
        foreach ($entry['results'] as $r) {
            if (is_array($r)) {
                $results[] = $r;
            }
        }
    }

    $results = pursuarr_post_filter(pursuarr_dedupe($results), $tokens);

    pursuarr_json([
        'results' => $results,
        'variantsUsed' => $used,
        'errors' => $errors,
    ]);
}

function pursuarr_action_grab(array $settings): void
{
    if (strtoupper((string)($_SERVER['REQUEST_METHOD'] ?? 'GET')) !== 'POST') {
        pursuarr_json(['ok' => false, 'error' => 'Use POST with a JSON body {guid, indexerId}.'], 405);
    }

    $raw = (string)file_get_contents('php://input');
    if (strlen($raw) > PURSUARR_MAX_GRAB_BODY) {
        pursuarr_json(['ok' => false, 'error' => 'Request body too large — send only {guid, indexerId}.'], 413);
    }

    $body = json_decode($raw, true);
    if (!is_array($body)) {
        pursuarr_json(['ok' => false, 'error' => 'Invalid JSON body — expected {guid, indexerId}.'], 400);
    }

    $guid = trim((string)($body['guid'] ?? ''));
    $indexerId = $body['indexerId'] ?? null;
    if ($guid === '') {
        pursuarr_json(['ok' => false, 'error' => 'Missing "guid" — search first, then grab from a result.'], 400);
    }
    if ($indexerId === null || $indexerId === '' || !is_numeric($indexerId)) {
        pursuarr_json(['ok' => false, 'error' => 'Missing or invalid "indexerId".'], 400);
    }

    $payload = ['guid' => $guid, 'indexerId' => (int)$indexerId];
    if ($settings['download_client_id'] !== null) {
        $payload['downloadClientId'] = $settings['download_client_id'];
    }

    $res = pursuarr_request_json('POST', '/search', $settings, null, $payload);
    if (!$res['ok']) {
        if ($res['http_code'] === 404) {
            pursuarr_json(['ok' => false, 'error' => "Release expired in Prowlarr's cache — search again."]);
        }
        pursuarr_json(['ok' => false, 'error' => (string)$res['error']]);
    }
    pursuarr_json(['ok' => true, 'response' => $res['json']]);
}

function pursuarr_action_indexers(array $settings): void
{
    $res = pursuarr_request_json('GET', '/indexer', $settings, null, null, 20);
    if (!$res['ok'] || !is_array($res['json'])) {
        pursuarr_json(['ok' => false, 'error' => (string)$res['error']], 502);
    }
    $out = [];
    foreach ($res['json'] as $item) {
        if (!is_array($item)) {
            continue;
        }
        $out[] = [
            'id' => $item['id'] ?? null,
            'name' => (string)($item['name'] ?? ''),
            'protocol' => (string)($item['protocol'] ?? ''),
            'enable' => (bool)($item['enable'] ?? true),
        ];
    }
    pursuarr_json($out);
}

function pursuarr_action_categories(array $settings): void
{
    $res = pursuarr_request_json('GET', '/categories', $settings, null, null, 20);
    if (!$res['ok'] || !is_array($res['json'])) {
        pursuarr_json([]);
    }
    $out = [];
    foreach ($res['json'] as $item) {
        if (!is_array($item)) {
            continue;
        }
        $subs = [];
        foreach ((array)($item['subCategories'] ?? []) as $sub) {
            if (is_array($sub)) {
                $subs[] = ['id' => $sub['id'] ?? null, 'name' => (string)($sub['name'] ?? '')];
            }
        }
        $out[] = [
            'id' => $item['id'] ?? null,
            'name' => (string)($item['name'] ?? ''),
            'subCategories' => $subs,
        ];
    }
    pursuarr_json($out);
}

function pursuarr_action_status(array $settings): void
{
    $url = $_GET['url'] ?? $_POST['url'] ?? null;
    $key = $_GET['key'] ?? $_POST['key'] ?? null;
    $verifyTls = $_GET['verify_tls'] ?? $_POST['verify_tls'] ?? null;

    if ($url !== null || $key !== null) {
        $settings = pursuarr_normalize_settings([
            'prowlarr_url' => (string)($url ?? $settings['prowlarr_url']),
            'prowlarr_api_key' => (string)($key ?? $settings['prowlarr_api_key']),
            'verify_tls' => $verifyTls === null ? $settings['verify_tls'] : !in_array((string)$verifyTls, ['0', 'false', 'off'], true),
        ]);
    }

    $res = pursuarr_request_json('GET', '/system/status', $settings, null, null, 20);
    if (!$res['ok']) {
        pursuarr_json(['ok' => false, 'error' => (string)$res['error'], 'url' => $settings['prowlarr_url']]);
    }
    $json = is_array($res['json']) ? $res['json'] : [];
    pursuarr_json([
        'ok' => true,
        'url' => $settings['prowlarr_url'],
        'version' => (string)($json['version'] ?? ''),
        'instanceName' => (string)($json['instanceName'] ?? ''),
    ]);
}

function pursuarr_action_parse(array $settings): void
{
    $query = (string)($_GET['query'] ?? '');
    $tokens = pursuarr_tokenize($query);
    $variants = pursuarr_plan_variants(
        $tokens,
        $settings['expansion_groups'],
        (int)$settings['max_search_variants']
    );
    $classified = [];
    foreach ($tokens as $t) {
        $classified[] = ['type' => $t['type'], 'text' => $t['text'], 'sent' => pursuarr_is_sent($t)];
    }
    pursuarr_json([
        'query' => $query,
        'tokens' => $classified,
        'prowlarrQuery' => pursuarr_base_query($tokens),
        'variants' => $variants,
    ]);
}

/* ------------------------------------------------------------------ HTML --- */

function pursuarr_render_fatal(string $message): void
{
    http_response_code(500);
    echo '<!doctype html><html><head><meta charset="utf-8"><title>Pursuarr</title>'
        . '<style>body{font:16px/1.5 system-ui,sans-serif;background:#0f1115;color:#e6e8ee;padding:40px}'
        . '.box{max-width:640px;margin:0 auto;background:#171a21;border:1px solid #262b36;border-radius:10px;padding:24px}'
        . 'code{background:#232837;padding:2px 6px;border-radius:4px}</style></head><body><div class="box">'
        . '<h1>Pursuarr</h1><p>' . $message . '</p></div></body></html>';
    exit;
}

function pursuarr_render_settings(?array $settings, bool $isSetup, ?string $notice, ?string $error): void
{
    $s = $settings ?? pursuarr_default_settings();
    $title = $isSetup ? 'Pursuarr — Setup' : 'Pursuarr — Settings';
    $heading = $isSetup ? 'Setup' : 'Settings';
    $submitLabel = $isSetup ? 'Save & connect' : 'Save settings';
    $groupsText = pursuarr_h(pursuarr_groups_to_text($s['expansion_groups']));
    ?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title><?= pursuarr_h($title) ?></title>
<style>
:root{--bg:#0f1115;--panel:#171a21;--text:#e6e8ee;--muted:#9aa3b2;--accent:#4f8cff;--border:#262b36;--danger:#ff6b6b;--ok:#3ddc97;--warn:#f0b429}
*{box-sizing:border-box}
body{margin:0;font:15px/1.5 system-ui,-apple-system,"Segoe UI",sans-serif;background:var(--bg);color:var(--text)}
.wrap{max-width:680px;margin:0 auto;padding:32px 20px}
h1{font-size:22px;margin:0 0 4px}
.sub{color:var(--muted);margin:0 0 24px}
.card{background:var(--panel);border:1px solid var(--border);border-radius:12px;padding:22px}
label{display:block;font-size:13px;color:var(--muted);margin:16px 0 6px}
input[type=text],input[type=number],textarea{width:100%;padding:10px 12px;border-radius:8px;border:1px solid var(--border);background:#0f1115;color:var(--text);font:inherit}
textarea{min-height:96px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:13px}
input:focus,textarea:focus{outline:2px solid var(--accent);outline-offset:1px}
.row{display:flex;gap:14px;flex-wrap:wrap}
.row>div{flex:1;min-width:180px}
.check{display:flex;align-items:center;gap:8px;margin:18px 0 0;color:var(--text);font-size:14px}
.check input{width:16px;height:16px}
button{font:inherit;border-radius:8px;border:1px solid var(--border);padding:10px 18px;cursor:pointer;background:#232837;color:var(--text)}
button.primary{background:var(--accent);border-color:var(--accent);color:#fff;font-weight:600}
button:hover{filter:brightness(1.1)}
.actions{margin-top:22px;display:flex;gap:10px;align-items:center;flex-wrap:wrap}
.msg{border-radius:8px;padding:12px 14px;margin:16px 0;font-size:14px}
.msg.ok{background:rgba(61,220,151,.12);border:1px solid rgba(61,220,151,.4);color:var(--ok)}
.msg.err{background:rgba(255,107,107,.12);border:1px solid rgba(255,107,107,.4);color:var(--danger)}
.msg.warn{background:rgba(240,180,41,.12);border:1px solid rgba(240,180,41,.4);color:var(--warn)}
.hint{color:var(--muted);font-size:12.5px;margin:6px 0 0}
#testResult{margin-top:10px;font-size:13.5px}
a{color:var(--accent)}
</style>
</head>
<body>
<div class="wrap">
  <h1>Pursuarr</h1>
  <p class="sub"><?= $isSetup ? 'First run — connect it to your Prowlarr instance.' : 'Edit your Pursuarr configuration.' ?></p>

  <?php if ($notice !== null): ?>
    <div class="msg ok"><?= pursuarr_h($notice) ?></div>
  <?php endif; ?>
  <?php if ($error !== null): ?>
    <div class="msg err"><?= pursuarr_h($error) ?></div>
  <?php endif; ?>

  <form class="card" method="post" action="?action=settings">
    <h2 style="margin:0;font-size:16px"><?= pursuarr_h($heading) ?></h2>

    <label for="prowlarr_url">Prowlarr base URL</label>
    <input type="text" id="prowlarr_url" name="prowlarr_url" value="<?= pursuarr_h($s['prowlarr_url']) ?>" placeholder="http://localhost:9696" required>

    <label for="prowlarr_api_key">Prowlarr API key</label>
    <input type="text" id="prowlarr_api_key" name="prowlarr_api_key" value="<?= pursuarr_h($s['prowlarr_api_key']) ?>" placeholder="Settings → General → Security → API Key" autocomplete="off">

    <label for="expansion_groups">Expand search groups <span style="opacity:.7">(one group per line, terms separated by <code>|</code>)</span></label>
    <textarea id="expansion_groups" name="expansion_groups" placeholder="x265 | h265 | HEVC"><?= $groupsText ?></textarea>
    <p class="hint">A search for <code>x265</code> then also searches <code>h265</code> and <code>HEVC</code>. Quoted, excluded and <code>{…}</code> tokens are never expanded.</p>

    <div class="row">
      <div>
        <label for="max_search_variants">Max search variants</label>
        <input type="number" id="max_search_variants" name="max_search_variants" min="1" max="20" value="<?= (int)$s['max_search_variants'] ?>">
      </div>
      <div>
        <label for="default_limit">Default result limit</label>
        <input type="number" id="default_limit" name="default_limit" min="1" max="1000" value="<?= (int)$s['default_limit'] ?>">
      </div>
      <div>
        <label for="search_timeout">Search timeout (seconds)</label>
        <input type="number" id="search_timeout" name="search_timeout" min="5" max="600" value="<?= (int)$s['search_timeout'] ?>">
      </div>
    </div>

    <label for="download_client_id">Download client ID <span style="opacity:.7">(optional — sent on grab)</span></label>
    <input type="text" id="download_client_id" name="download_client_id" value="<?= pursuarr_h($s['download_client_id'] === null ? '' : (string)$s['download_client_id']) ?>" placeholder="e.g. 1">

    <label class="check"><input type="checkbox" id="verify_tls" name="verify_tls" value="1" <?= $s['verify_tls'] ? 'checked' : '' ?>> Verify TLS certificates</label>
    <p class="hint">Uncheck for self-signed certificates.</p>

    <div class="actions">
      <button type="submit" class="primary"><?= pursuarr_h($submitLabel) ?></button>
      <button type="button" id="testBtn">Test connection</button>
      <?php if (!$isSetup): ?>
        <a href="./">← back to search</a>
      <?php endif; ?>
    </div>
    <div id="testResult"></div>
    <p class="hint">Settings are written to <code>settings.php</code> (chmod 0600). Keep it outside the web root when possible; otherwise a <code>.htaccess</code> deny rule is written alongside it.</p>
    <p class="hint">Note: this app has no login of its own — protect it at your reverse proxy.</p>
  </form>
</div>
<script>
(function(){
  var btn = document.getElementById('testBtn');
  var out = document.getElementById('testResult');
  btn.addEventListener('click', function(){
    var params = new URLSearchParams();
    params.set('action', 'status');
    params.set('url', document.getElementById('prowlarr_url').value.trim());
    params.set('key', document.getElementById('prowlarr_api_key').value.trim());
    params.set('verify_tls', document.getElementById('verify_tls').checked ? '1' : '0');
    out.textContent = 'Testing…';
    out.style.color = 'var(--muted)';
    fetch('?' + params.toString())
      .then(function(r){ return r.json(); })
      .then(function(d){
        if (d.ok) {
          out.textContent = 'Connected' + (d.instanceName ? ' to ' + d.instanceName : '') + (d.version ? ' (Prowlarr ' + d.version + ')' : '') + '.';
          out.style.color = 'var(--ok)';
        } else {
          out.textContent = d.error || 'Connection failed.';
          out.style.color = 'var(--danger)';
        }
      })
      .catch(function(){ out.textContent = 'Connection test failed.'; out.style.color = 'var(--danger)'; });
  });
})();
</script>
</body>
</html>
    <?php
}

function pursuarr_render_app(array $settings): void
{
    $boot = json_encode(
        [
            'defaultLimit' => (int)$settings['default_limit'],
            'searchTimeout' => (int)$settings['search_timeout'],
        ],
        JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT
    );
    ?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Pursuarr</title>
<style>
:root{--bg:#0f1115;--panel:#171a21;--panel2:#1c212b;--text:#e6e8ee;--muted:#9aa3b2;--accent:#4f8cff;--border:#262b36;--danger:#ff6b6b;--ok:#3ddc97;--warn:#f0b429;--torrent:#3ddc97;--usenet:#4f8cff}
*{box-sizing:border-box}
body{margin:0;font:15px/1.45 system-ui,-apple-system,"Segoe UI",sans-serif;background:var(--bg);color:var(--text)}
header{display:flex;align-items:center;gap:12px;padding:12px 20px;background:var(--panel);border-bottom:1px solid var(--border);position:sticky;top:0;z-index:30}
header h1{font-size:17px;margin:0;letter-spacing:.4px}
header .tag{color:var(--muted);font-size:12px;border:1px solid var(--border);border-radius:999px;padding:2px 10px}
.spacer{flex:1}
main{max-width:1440px;margin:0 auto;padding:18px 20px 60px}
.panel{background:var(--panel);border:1px solid var(--border);border-radius:12px;padding:16px}
.searchrow{display:flex;gap:10px;flex-wrap:wrap}
#q{flex:1;min-width:260px;padding:12px 14px;font-size:16px;border-radius:10px;border:1px solid var(--border);background:#0f1115;color:var(--text)}
#q:focus{outline:2px solid var(--accent);outline-offset:1px}
select,input[type=number]{padding:10px 12px;border-radius:10px;border:1px solid var(--border);background:#0f1115;color:var(--text);font:inherit}
button{font:inherit;border-radius:10px;border:1px solid var(--border);padding:10px 16px;cursor:pointer;background:#232837;color:var(--text)}
button.primary{background:var(--accent);border-color:var(--accent);color:#fff;font-weight:600}
button.ghost{background:transparent}
button:disabled{opacity:.55;cursor:default}
button:hover:not(:disabled){filter:brightness(1.12)}
.hint{color:var(--muted);font-size:12.5px;margin:10px 2px 0}
.hint code{background:#232837;padding:1px 5px;border-radius:4px;font-size:11.5px}
.warnhint{margin:10px 2px 0;font-size:12.5px;color:var(--warn)}
.variants{margin:12px 2px 0;display:flex;gap:8px;flex-wrap:wrap;align-items:center}
.variants .vlabel{color:var(--muted);font-size:12px}
.chip{background:#232837;border:1px solid var(--border);border-radius:999px;padding:3px 11px;font-size:12px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace}
.errors{margin:12px 2px 0}
.errors .err{background:rgba(255,107,107,.1);border:1px solid rgba(255,107,107,.35);color:var(--danger);border-radius:8px;padding:8px 12px;font-size:13px;margin-top:6px}
.filters{display:flex;gap:18px;flex-wrap:wrap;align-items:flex-end;margin-top:14px}
.filters .fgroup{display:flex;flex-direction:column;gap:6px}
.filters label{font-size:12px;color:var(--muted)}
details.dd{position:relative}
details.dd>summary{list-style:none;cursor:pointer;padding:10px 12px;border:1px solid var(--border);border-radius:10px;background:#0f1115;min-width:210px;user-select:none}
details.dd>summary::-webkit-details-marker{display:none}
details.dd[open]>summary{border-color:var(--accent)}
.ddpanel{position:absolute;top:calc(100% + 6px);left:0;z-index:40;background:var(--panel2);border:1px solid var(--border);border-radius:10px;padding:10px;min-width:260px;max-height:320px;overflow:auto;box-shadow:0 12px 30px rgba(0,0,0,.45)}
.ddpanel .row{display:flex;align-items:center;gap:8px;padding:5px 4px;font-size:13.5px}
.ddpanel .row input{width:15px;height:15px}
.ddpanel .sub{padding-left:18px;color:var(--muted)}
#limit{width:96px}
.meta{margin:16px 2px 8px;color:var(--muted);font-size:13px;display:flex;align-items:center;gap:10px;min-height:20px}
.spin{width:15px;height:15px;border:2px solid var(--border);border-top-color:var(--accent);border-radius:50%;animation:sp .8s linear infinite}
@keyframes sp{to{transform:rotate(360deg)}}
.tablewrap{overflow-x:auto;border:1px solid var(--border);border-radius:12px;background:var(--panel)}
table{width:100%;border-collapse:collapse;font-size:13.5px}
th,td{padding:9px 12px;text-align:left;border-bottom:1px solid var(--border);vertical-align:top}
th{position:sticky;top:0;background:var(--panel2);color:var(--muted);font-weight:600;font-size:12px;letter-spacing:.3px;white-space:nowrap}
th.sortable{cursor:pointer;user-select:none}
th.sortable:hover{color:var(--text)}
th .arr{opacity:.55;font-size:10px}
tbody tr:hover{background:rgba(79,140,255,.06)}
td.title{min-width:320px;word-break:break-word}
td.title a{color:var(--text);text-decoration:none}
td.title a:hover{color:var(--accent);text-decoration:underline}
.badge{display:inline-block;border-radius:999px;padding:1px 9px;font-size:11px;font-weight:600;border:1px solid var(--border)}
.badge.torrent{color:var(--torrent);border-color:rgba(61,220,151,.4)}
.badge.usenet{color:var(--usenet);border-color:rgba(79,140,255,.4)}
.cat{color:var(--muted);font-size:12px}
.links a{color:var(--accent);text-decoration:none;margin-right:8px;font-size:12px}
.links a:hover{text-decoration:underline}
.num{font-variant-numeric:tabular-nums;white-space:nowrap}
.empty{padding:34px;text-align:center;color:var(--muted)}
#toasts{position:fixed;right:18px;bottom:18px;display:flex;flex-direction:column;gap:10px;z-index:100}
.toast{background:var(--panel2);border:1px solid var(--border);border-left:3px solid var(--accent);border-radius:10px;padding:12px 16px;font-size:13.5px;max-width:380px;box-shadow:0 10px 30px rgba(0,0,0,.4)}
.toast.ok{border-left-color:var(--ok)}
.toast.err{border-left-color:var(--danger)}
a{color:var(--accent)}
.hidden{display:none !important}
</style>
</head>
<body>
<header>
  <h1>Pursuarr</h1>
  <span class="tag">Prowlarr search</span>
  <div class="spacer"></div>
  <a class="ghost" style="padding:8px 12px;border:1px solid var(--border);border-radius:10px;text-decoration:none;color:var(--text)" href="?action=settings">Settings</a>
</header>
<main>
  <section class="panel">
    <div class="searchrow">
      <input id="q" type="text" placeholder="Search — e.g.  S01 -S01E  &quot;green&quot;  x265" autocomplete="off" spellcheck="false">
      <select id="type" title="Search type">
        <option value="search">search</option>
        <option value="tvsearch">tvsearch</option>
        <option value="movie">movie</option>
        <option value="music">music</option>
        <option value="book">book</option>
      </select>
      <button id="go" class="primary">Search</button>
      <button id="cancel" class="ghost hidden">Cancel</button>
    </div>
    <div class="hint">
      <code>-term</code> exclude &nbsp;·&nbsp; <code>"exact phrase"</code> whole-word match &nbsp;·&nbsp;
      <code>-"exact phrase"</code> exclude it &nbsp;·&nbsp; <code>{TvdbId:71663}</code> Prowlarr ID &nbsp;·&nbsp;
      codec aliases expand automatically (x265 → h265/HEVC). Long searches can hit PHP-FPM / reverse-proxy
      timeouts (Cloudflare ~100 s) — press Cancel or narrow the query.
    </div>
    <div id="idhint" class="warnhint hidden">
      ID tokens like <code>{TvdbId:…}</code> are only parsed as IDs by Prowlarr for tvsearch/movie —
      switch the type selector for reliable ID-based search.
    </div>
    <div class="variants" id="variants"></div>
    <div class="errors" id="searchErrors"></div>
  </section>

  <section class="filters">
    <div class="fgroup">
      <label>Indexers</label>
      <details class="dd" id="ddIndexers">
        <summary id="indexersSummary">All indexers</summary>
        <div class="ddpanel" id="indexerList"><div class="row" style="color:var(--muted)">Loading…</div></div>
      </details>
    </div>
    <div class="fgroup">
      <label for="category">Category</label>
      <select id="category"><option value="">All categories</option></select>
    </div>
    <div class="fgroup">
      <label for="limit">Limit</label>
      <input type="number" id="limit" min="1" max="1000" value="100">
    </div>
  </section>

  <div class="meta" id="meta"></div>

  <div class="tablewrap">
    <table id="tbl">
      <thead>
        <tr>
          <th class="sortable" data-sort="title">Title</th>
          <th>Category</th>
          <th class="sortable" data-sort="age">Age</th>
          <th class="sortable" data-sort="size">Size</th>
          <th class="sortable" data-sort="seeders">Seeders / Grabs</th>
          <th class="sortable" data-sort="indexer">Indexer</th>
          <th>Proto</th>
          <th>Links</th>
          <th></th>
        </tr>
      </thead>
      <tbody id="rows"></tbody>
    </table>
  </div>
</main>
<div id="toasts"></div>
<script>
window.PURSUARR = <?= $boot ?>;
(function(){
'use strict';

var qEl = document.getElementById('q');
var typeEl = document.getElementById('type');
var goBtn = document.getElementById('go');
var cancelBtn = document.getElementById('cancel');
var metaEl = document.getElementById('meta');
var rowsEl = document.getElementById('rows');
var variantsEl = document.getElementById('variants');
var errorsEl = document.getElementById('searchErrors');
var idHintEl = document.getElementById('idhint');
var limitEl = document.getElementById('limit');
var categoryEl = document.getElementById('category');
var indexersListEl = document.getElementById('indexerList');
var indexersSummaryEl = document.getElementById('indexersSummary');

limitEl.value = String(window.PURSUARR.defaultLimit || 100);

var state = {
  results: [],
  sortKey: 'age',
  sortDir: 'asc',
  searched: false
};
var controller = null;

function el(tag, cls, text){
  var n = document.createElement(tag);
  if (cls) n.className = cls;
  if (text !== undefined && text !== null) n.textContent = String(text);
  return n;
}

function toast(message, kind){
  var box = document.getElementById('toasts');
  var t = el('div', 'toast ' + (kind || ''));
  t.textContent = message;
  box.appendChild(t);
  setTimeout(function(){
    t.style.opacity = '0';
    t.style.transition = 'opacity .4s';
    setTimeout(function(){ if (t.parentNode) t.parentNode.removeChild(t); }, 450);
  }, kind === 'err' ? 7000 : 4500);
}

function safeUrl(u){
  if (typeof u !== 'string' || u === '') return null;
  if (/^(https?:|magnet:)/i.test(u)) return u;
  return null;
}

function formatSize(n){
  if (n === null || n === undefined || isNaN(Number(n))) return '—';
  var units = ['B','KB','MB','GB','TB','PB'];
  var x = Number(n), i = 0;
  while (x >= 1024 && i < units.length - 1){ x /= 1024; i++; }
  if (i === 0) return x + ' B';
  return (x >= 100 ? x.toFixed(0) : x.toFixed(1)) + ' ' + units[i];
}

function ageMinutes(r){
  if (r.publishDate){
    var t = Date.parse(r.publishDate);
    if (!isNaN(t)) return Math.max(0, (Date.now() - t) / 60000);
  }
  if (r.ageMinutes !== undefined && r.ageMinutes !== null && !isNaN(Number(r.ageMinutes))) return Number(r.ageMinutes);
  if (r.ageHours !== undefined && r.ageHours !== null && !isNaN(Number(r.ageHours))) return Number(r.ageHours) * 60;
  if (r.age !== undefined && r.age !== null && !isNaN(Number(r.age))) return Number(r.age) * 1440;
  return null;
}

function formatAge(r){
  var m = ageMinutes(r);
  if (m === null) return '—';
  if (m < 60) return Math.max(1, Math.floor(m)) + 'm';
  if (m < 2880) return Math.floor(m / 60) + 'h';
  return Math.floor(m / 1440) + 'd';
}

function categoryText(r){
  var cats = r.categories;
  if (!cats || !cats.length) return '—';
  var names = [];
  for (var i = 0; i < cats.length; i++){
    var c = cats[i];
    if (c && typeof c === 'object') names.push(String(c.name || c.id || ''));
    else names.push(String(c));
  }
  return names.filter(Boolean).join(', ') || '—';
}

function renderVariants(list){
  variantsEl.innerHTML = '';
  if (!list || !list.length) return;
  variantsEl.appendChild(el('span', 'vlabel', list.length > 1 ? 'searched:' : 'searched:'));
  for (var i = 0; i < list.length; i++){
    variantsEl.appendChild(el('span', 'chip', list[i]));
  }
}

function renderErrors(list){
  errorsEl.innerHTML = '';
  if (!list || !list.length) return;
  for (var i = 0; i < list.length; i++){
    var e = list[i];
    var d = el('div', 'err');
    d.textContent = (e.variant ? 'Variant "' + e.variant + '": ' : '') + (e.error || 'Unknown error');
    errorsEl.appendChild(d);
  }
}

function sortValue(r, key){
  switch (key){
    case 'title': return String(r.title || '').toLowerCase();
    case 'age': { var m = ageMinutes(r); return m === null ? Number.MAX_SAFE_INTEGER : m; }
    case 'size': return Number(r.size) || 0;
    case 'seeders': return String(r.protocol || '').toLowerCase() === 'usenet' ? (Number(r.grabs) || 0) : (Number(r.seeders) || 0);
    case 'indexer': return String(r.indexer || '').toLowerCase();
  }
  return 0;
}

function renderRows(){
  rowsEl.innerHTML = '';
  var arr = state.results.slice();
  arr.sort(function(a, b){
    var va = sortValue(a, state.sortKey), vb = sortValue(b, state.sortKey);
    var c = 0;
    if (typeof va === 'string' && typeof vb === 'string') c = va < vb ? -1 : (va > vb ? 1 : 0);
    else c = va - vb;
    if (c === 0) c = String(a.title || '') < String(b.title || '') ? -1 : (String(a.title || '') > String(b.title || '') ? 1 : 0);
    return state.sortDir === 'asc' ? c : -c;
  });

  if (!arr.length){
    var tr = el('tr');
    var td = el('td', 'empty', state.searched ? 'No results.' : 'Search something to get started.');
    td.colSpan = 9;
    tr.appendChild(td);
    rowsEl.appendChild(tr);
    return;
  }

  for (var i = 0; i < arr.length; i++){
    var r = arr[i];
    var tr = el('tr');

    var tdTitle = el('td', 'title');
    var infoUrl = safeUrl(r.infoUrl);
    if (infoUrl){
      var a = el('a', null, String(r.title || '(untitled)'));
      a.href = infoUrl;
      a.target = '_blank';
      a.rel = 'noopener noreferrer';
      tdTitle.appendChild(a);
    } else {
      tdTitle.appendChild(el('span', null, String(r.title || '(untitled)')));
    }
    tr.appendChild(tdTitle);

    tr.appendChild(el('td', 'cat', categoryText(r)));
    tr.appendChild(el('td', 'num', formatAge(r)));
    tr.appendChild(el('td', 'num', formatSize(r.size)));

    var seed = '—';
    if (String(r.protocol || '').toLowerCase() === 'usenet'){
      if (r.grabs !== undefined && r.grabs !== null) seed = String(r.grabs);
    } else if (r.seeders !== undefined && r.seeders !== null){
      seed = String(r.seeders);
      if (r.leechers !== undefined && r.leechers !== null) seed += ' / ' + String(r.leechers);
    }
    tr.appendChild(el('td', 'num', seed));

    tr.appendChild(el('td', null, String(r.indexer || '—')));

    var tdProto = el('td');
    var proto = String(r.protocol || '').toLowerCase();
    var badge = el('span', 'badge ' + proto, proto || '?');
    tdProto.appendChild(badge);
    tr.appendChild(tdProto);

    var tdLinks = el('td', 'links');
    var commentUrl = safeUrl(r.commentUrl);
    var magnetUrl = safeUrl(r.magnetUrl);
    if (commentUrl){
      var ac = el('a', null, 'comment');
      ac.href = commentUrl; ac.target = '_blank'; ac.rel = 'noopener noreferrer';
      tdLinks.appendChild(ac);
    }
    if (magnetUrl){
      var am = el('a', null, 'magnet');
      am.href = magnetUrl;
      tdLinks.appendChild(am);
    }
    if (!commentUrl && !magnetUrl) tdLinks.appendChild(el('span', null, '—'));
    tr.appendChild(tdLinks);

    var tdGrab = el('td');
    var grabBtn = el('button', 'primary', 'Grab');
    grabBtn.type = 'button';
    (function(row, btn){
      btn.addEventListener('click', function(){ grab(row, btn); });
    })(r, grabBtn);
    tdGrab.appendChild(grabBtn);
    tr.appendChild(tdGrab);

    rowsEl.appendChild(tr);
  }

  var heads = document.querySelectorAll('th.sortable');
  for (var h = 0; h < heads.length; h++){
    var th = heads[h];
    var key = th.getAttribute('data-sort');
    var base = th.textContent.replace(/[▲▼]\s*$/, '').trim();
    th.textContent = base;
    if (key === state.sortKey){
      th.appendChild(document.createTextNode(' ' + (state.sortDir === 'asc' ? '▲' : '▼')));
    }
  }
}

function setBusy(busy){
  goBtn.disabled = busy;
  cancelBtn.classList.toggle('hidden', !busy);
  if (busy){
    metaEl.innerHTML = '';
    metaEl.appendChild(el('span', 'spin'));
    metaEl.appendChild(el('span', null, 'Searching…'));
  }
}

function updateIdHint(){
  var hasId = /\{[^}]+\}/.test(qEl.value);
  idHintEl.classList.toggle('hidden', !(hasId && typeEl.value === 'search'));
}

function currentQuery(){ return qEl.value.trim(); }

function runSearch(){
  var query = currentQuery();
  if (!query){
    state.results = [];
    state.searched = false;
    renderRows();
    renderVariants([]);
    renderErrors([]);
    metaEl.textContent = '';
    return;
  }
  if (controller) controller.abort();
  controller = new AbortController();
  var signal = controller.signal;

  setBusy(true);

  var params = new URLSearchParams();
  params.set('action', 'search');
  params.set('query', query);
  params.set('type', typeEl.value);
  params.set('limit', String(limitEl.value || window.PURSUARR.defaultLimit));
  var ids = selectedIndexerIds();
  if (ids.length) params.set('indexerIds', ids.join(','));
  if (categoryEl.value) params.set('categories', categoryEl.value);

  fetch('?' + params.toString(), {signal: signal})
    .then(function(res){ return res.json(); })
    .then(function(data){
      if (signal.aborted) return;
      state.results = Array.isArray(data.results) ? data.results : [];
      state.searched = true;
      renderVariants(data.variantsUsed || []);
      renderErrors(data.errors || []);
      renderRows();
      metaEl.textContent = state.results.length + ' result' + (state.results.length === 1 ? '' : 's')
        + (data.errors && data.errors.length ? ' · ' + data.errors.length + ' variant error' + (data.errors.length === 1 ? '' : 's') : '');
    })
    .catch(function(err){
      if (err && err.name === 'AbortError') return;
      state.results = [];
      state.searched = true;
      renderRows();
      renderErrors([{variant: '', error: 'Request failed: ' + (err && err.message ? err.message : 'network error')}]);
      metaEl.textContent = '';
    })
    .then(function(){
      if (!signal.aborted) setBusy(false);
    });
}

function grab(row, btn){
  var guid = row.guid;
  var indexerId = row.indexerId;
  if (!guid || indexerId === undefined || indexerId === null){
    toast('This result has no grab information.', 'err');
    return;
  }
  btn.disabled = true;
  fetch('?action=grab', {
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    body: JSON.stringify({guid: guid, indexerId: indexerId})
  })
    .then(function(res){ return res.json(); })
    .then(function(data){
      if (data.ok){
        btn.textContent = 'Grabbed';
        toast('Sent to download client: ' + (row.title || guid), 'ok');
      } else {
        btn.disabled = false;
        toast(data.error || 'Grab failed.', 'err');
      }
    })
    .catch(function(){
      btn.disabled = false;
      toast('Grab request failed.', 'err');
    });
}

function selectedIndexerIds(){
  var boxes = indexersListEl.querySelectorAll('input[type=checkbox][data-id]');
  var ids = [];
  for (var i = 0; i < boxes.length; i++){
    if (boxes[i].checked) ids.push(boxes[i].getAttribute('data-id'));
  }
  return ids;
}

function updateIndexersSummary(){
  var boxes = indexersListEl.querySelectorAll('input[type=checkbox][data-id]');
  var checked = 0;
  for (var i = 0; i < boxes.length; i++) if (boxes[i].checked) checked++;
  indexersSummaryEl.textContent = checked === 0 ? 'All indexers'
    : checked + ' indexer' + (checked === 1 ? '' : 's') + ' selected';
}

function loadIndexers(){
  fetch('?action=indexers')
    .then(function(res){ return res.json(); })
    .then(function(data){
      indexersListEl.innerHTML = '';
      if (!Array.isArray(data)){
        indexersListEl.appendChild(el('div', 'row', data && data.error ? data.error : 'Failed to load indexers.'));
        return;
      }
      if (!data.length){
        indexersListEl.appendChild(el('div', 'row', 'No indexers configured in Prowlarr.'));
        return;
      }
      for (var i = 0; i < data.length; i++){
        var idx = data[i];
        var row = el('div', 'row');
        var cb = el('input');
        cb.type = 'checkbox';
        cb.setAttribute('data-id', String(idx.id));
        cb.addEventListener('change', function(){ updateIndexersSummary(); });
        var lab = el('label');
        lab.style.cursor = 'pointer';
        lab.appendChild(cb);
        lab.appendChild(document.createTextNode(' ' + (idx.name || '#' + idx.id) + (idx.enable ? '' : ' (disabled)')));
        row.appendChild(lab);
        indexersListEl.appendChild(row);
      }
    })
    .catch(function(){
      indexersListEl.innerHTML = '';
      indexersListEl.appendChild(el('div', 'row', 'Failed to load indexers.'));
    });
}

function loadCategories(){
  fetch('?action=categories')
    .then(function(res){ return res.json(); })
    .then(function(data){
      if (!Array.isArray(data)) return;
      for (var i = 0; i < data.length; i++){
        var c = data[i];
        var o = el('option', null, c.name || String(c.id));
        o.value = String(c.id);
        categoryEl.appendChild(o);
        var subs = c.subCategories || [];
        for (var j = 0; j < subs.length; j++){
          var s = subs[j];
          var so = el('option', null, '  ' + (s.name || String(s.id)));
          so.value = String(s.id);
          categoryEl.appendChild(so);
        }
      }
    })
    .catch(function(){});
}

goBtn.addEventListener('click', function(){
  runSearch();
});

cancelBtn.addEventListener('click', function(){
  if (controller) controller.abort();
  setBusy(false);
});

qEl.addEventListener('input', updateIdHint);

qEl.addEventListener('keydown', function(ev){
  if (ev.key === 'Enter'){
    runSearch();
  }
});

typeEl.addEventListener('change', updateIdHint);

limitEl.addEventListener('change', function(){
  if (currentQuery()) runSearch();
});
categoryEl.addEventListener('change', function(){
  if (currentQuery()) runSearch();
});

var heads = document.querySelectorAll('th.sortable');
for (var h = 0; h < heads.length; h++){
  (function(th){
    th.addEventListener('click', function(){
      var key = th.getAttribute('data-sort');
      if (state.sortKey === key){
        state.sortDir = state.sortDir === 'asc' ? 'desc' : 'asc';
      } else {
        state.sortKey = key;
        state.sortDir = 'asc';
      }
      renderRows();
    });
  })(heads[h]);
}

loadIndexers();
loadCategories();
renderRows();
qEl.focus();
})();
</script>
</body>
</html>
    <?php
}

if (!defined('PURSUARR_NO_DISPATCH')) {
    pursuarr_main();
}
